name: Build and Release for Azure Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and build
      run: |
        cd ./azure-pipeline/src
        npm install

    - name: Install tfx-cli
      run: |
        npm install -g tfx-cli

    - name: Create extension
      run: |
        cd  azure-pipeline
        tfx extension create --manifest-globs ./vss-extension.json

    - name: Upload VSIX file
      uses: actions/upload-artifact@v4
      with:
        name: VSIX file
        path: ./azure-pipeline/*.vsix
